### ISSUE TITLE
python RainCloud order of values

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [RainCloudPlots/RainCloudPlots#19]
Hi there it would be great if the order of the groups in the python version of the rainclould plot could be provided like in the half_violinplot.

**Comment by pog87** [comment]
@BenjaminSchwessinger thank you! This is an interesting option I have not thought about! I will add it in the next release of PtitPrince.

**Comment by pog87** [comment]
fixed 
`pip install ptitprince==0.1.4`
