### ISSUE TITLE
Update python tutorial to work with pip installed ptitprince

### ISSUE THREAD

**Issue by KirstieJane** [RainCloudPlots/RainCloudPlots#2]
Currently we have the `PtitPrince.py` file shipped with this repository but it should be updated so that the tutorial calls the pip version of this library.

**Comment by KirstieJane** [comment]
I had tried this locally and it didn’t work (after deleting the local copy of the code!) I can try again with the specific version tomorrow (Tuesday) morning.

Once it works for me I can add it to the requirements.txt file and it will install to binder.

**Comment by pog87** [comment]
Yes, locally youmay  still have a cached version of the old package...you can try

```
pip install --upgrade --no-deps --force-reinstall ptitprince
```

**Comment by KirstieJane** [comment]
Fixed! And updated in master :tada:
