### ISSUE TITLE
request: beeswarm option in instead of random jittered drops

### ISSUE THREAD

**Issue by denOudenLab** [RainCloudPlots/RainCloudPlots#23]
Thanks for the great code. Would it be possible to plot the 'raindrops' not in a random jitter but rather as a beeswarm? In matlab there's already pretty good code to implement this, perhaps also in python / R:

https://nl.mathworks.com/matlabcentral/fileexchange/37105-plot-spread-points-beeswarm-plot

This would really make the distributions much clearer, and particularly at the tail ends easier to see where distributions differ. 

Hanneke

**Comment by pog87** [comment]
in Python it's pretty simple to do
in this code
```python
pal = "Set2"
f, ax = plt.subplots(figsize=(7, 5))
ax=pt.half_violinplot( x = dx, y = dy, data = df, palette = pal, bw = .2, cut = 0.,
                      scale = "area", width = .6, inner = None, orient = ort)
ax=sns.stripplot( x = dx, y = dy, data = df, palette = pal, edgecolor = "white",
                 size = 3, jitter = 1, zorder = 0, orient = ort)
ax=sns.boxplot( x = dx, y = dy, data = df, color = "black", width = .15, zorder = 10,\
            showcaps = True, boxprops = {'facecolor':'none', "zorder":10},\
            showfliers=True, whiskerprops = {'linewidth':2, "zorder":10},\
               saturation = 1, orient = ort)
```
just substituting `stripplot` with `swarmplot` shold do.

I don't think I'm adding this feature, for the moment. Thank you for your suggestion anyway! 👍
