### ISSUE TITLE
Python Environment Locally Not Loading

### ISSUE THREAD

**Issue by tylerjwenzel** [RainCloudPlots/RainCloudPlots#28]
Hi,

I can run the environment in a jupyter notebook, but following the tutorial, I cannot get the environment working anyway else. This results in everything after step [11] (the automation step) not outputting anything different.

Would you have any input on how to get the script to work locally, through a command line interface? I was hoping to run the python script without needing to boot up a jupyter notebook.

I have ran the following:

`pip install ptitprince
conda create --name rainpy python=3.6
activate rainpy
pip install -r requirements.txt
conda install nb_conda`

However, this doesn't allow me to run a python script from a command line
`python rainplot.py`

I am probably going to figure it out momentarily, but the tutorial on my end doesn't seem to allow you to load the environment to be useable after the automation step from a command line.

**Comment by pog87** [comment]
Hello!
Thanks for the report.

Yes, the script version should be a little different... you can try to change each plotting cell from

```python
dx = "group"; dy = "score"; ort = "h"; pal = "Set2"; sigma = .2
ax=pt.RainCloud(x = dx, y = dy, data = df, palette = pal, bw = sigma,
                 width_viol = .6, figsize = (7,5), orient = ort)
'''

to something like this

```python
f, ax = plt.subplots(figsize=(7, 5))
dx = "group"; dy = "score"; ort = "h"; pal = "Set2"; sigma = .2
ax=pt.RainCloud(x = dx, y = dy, data = df, palette = pal, bw = sigma,
                 width_viol = .6, ax = ax, orient = ort)
f.show()
'''

**Comment by tylerjwenzel** [comment]
Thank you, that seemed to work.
