### ISSUE TITLE
Python: Printout Documentation Recommendations

### ISSUE THREAD

**Issue by tylerjwenzel** [RainCloudPlots/RainCloudPlots#29]
Hi,

One more inquiry - it might be part of matlab plotting the graph. I havn't quite figured out if its a parameter on your behalf or matlab's. I think the spacing might be, but the x-axis offset is matlab.

I think it would be beneficial to have documentation describing how to modify the printout spacing of the graph. For example, is there a way to reduce the spacing in between treatments?

```
# coding: utf8

import pandas as pd
import ptitprince as pt
import seaborn as sns
import os
import matplotlib.pyplot as plt
#sns.set(style="darkgrid")
#sns.set(style="whitegrid")
#sns.set_style("white")
sns.set(style="whitegrid",font_scale=2)
import matplotlib.collections as clt

df = pd.read_csv ("[filename].csv", sep= ",")
df.head()

savefigs = True
figs_dir = 'figs'

if savefigs:
    # Make the figures folder if it doesn't yet exist
    if not os.path.isdir('figs'):
        os.makedirs('figs')

f, ax = plt.subplots(figsize=(15, 5))
dx = "Treatment"; dy = "score"; ort = "v"; pal = "Set2"; sigma = .2
ax=pt.RainCloud(x = dx, y = dy, data = df, palette = pal, bw = sigma,
                 width_viol = .6, ax = ax, move=.2, offset=.1, orient = ort, pointplot = True)
f.show()

if savefigs:
    f.savefig('figs/figure20.png', bbox_inches='tight')
```

<img width="981" alt="Screen Shot 2019-03-13 at 2 10 38 PM" src="https://user-images.githubusercontent.com/48533399/54316451-0acf0700-459e-11e9-831b-08f8bb046664.png">

Also, if I wanted to emphasize the distribution plot by increasing the viol_width as follows:

```
# coding: utf8

import pandas as pd
import ptitprince as pt
import seaborn as sns
import os
import matplotlib.pyplot as plt
#sns.set(style="darkgrid")
#sns.set(style="whitegrid")
#sns.set_style("white")
sns.set(style="whitegrid",font_scale=2)
import matplotlib.collections as clt

df = pd.read_csv ("[filename].csv", sep= ",")
df.head()

savefigs = True
figs_dir = 'figs'

if savefigs:
    # Make the figures folder if it doesn't yet exist
    if not os.path.isdir('figs'):
        os.makedirs('figs')

f, ax = plt.subplots(figsize=(15, 5))
dx = "Treatment"; dy = "score"; ort = "v"; pal = "Set2"; sigma = .2
ax=pt.RainCloud(x = dx, y = dy, data = df, palette = pal, bw = sigma,
                 width_viol = .9, ax = ax, move=.2, offset=.1, orient = ort)
f.show()

if savefigs:
    f.savefig('figs/figure20.png', bbox_inches='tight')
```

<img width="769" alt="Screen Shot 2019-03-13 at 2 44 50 PM" src="https://user-images.githubusercontent.com/48533399/54316680-9779c500-459e-11e9-9ec5-2ecd75f1a15b.png">

How would I go about offsetting the x-axis so that the first plot did not get cut off by the x-axis?

**Comment by pog87** [comment]
Could you please show the code blocks that generated the figures?

**Comment by tylerjwenzel** [comment]
`# coding: utf8

import pandas as pd
import ptitprince as pt
import seaborn as sns
import os
import matplotlib.pyplot as plt
#sns.set(style="darkgrid")
#sns.set(style="whitegrid")
#sns.set_style("white")
sns.set(style="whitegrid",font_scale=2)
import matplotlib.collections as clt

df = pd.read_csv ("[filename].csv", sep= ",")
df.head()

savefigs = True
figs_dir = 'figs'

if savefigs:
    # Make the figures folder if it doesn't yet exist
    if not os.path.isdir('figs'):
        os.makedirs('figs')

f, ax = plt.subplots(figsize=(15, 5))
dx = "Treatment"; dy = "score"; ort = "v"; pal = "Set2"; sigma = .2
ax=pt.RainCloud(x = dx, y = dy, data = df, palette = pal, bw = sigma,
                 width_viol = .9, ax = ax, move=.2, offset=.1, orient = ort, pointplot = True)
f.show()

if savefigs:
    f.savefig('figs/figure20.png', bbox_inches='tight')
`

**Comment by pog87** [comment]
Ok, now I get what you mean.

In the first figure I would change the figsize, for instance

```python
f, ax = plt.subplots(figsize=(12, 5))
dx = "Treatment"; dy = "score"; ort = "v"; pal = "Set2"; sigma = .2
ax=pt.RainCloud(x = dx, y = dy, data = df, palette = pal, bw = sigma,
                 width_viol = .6, ax = ax, move=.2, offset=.1, orient = ort, pointplot = True)
f.show()
```

in the second I would increase the figsize in the x-axis, like this
```python
f, ax = plt.subplots(figsize=(18, 5))
```
and/or dicrease a bit the `viol_width` value

Alas, this kind of adjustment is data-dependent, and cannot be treated in a general tutorial. 
The default options of pt.RainCloud offer a proper plot for any dataset. To customize it in deep, the user should refer to matplotlib/seaborn tutorials.
