### ISSUE TITLE
Add R package dependencies to `install.R`

### ISSUE THREAD

**Issue by ha0ye** [RainCloudPlots/RainCloudPlots#3]
The RStudio binder example was taking a while, and I think it's due to `R_rainclouds.R` checking for and then installing several packages that aren't included in `install.R`.

The code appears to be
```
packages <- c("cowplot", "readr", "ggplot2" , "dplyr", "lavaan", "smooth", "Hmisc")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
```

I think `readr`, `ggplot2`, and `dplyr` are included already in `install.R` either directly, or as part of the `tidyverse` package. Adding the rest to `install.R` would make the example run smoother.

**Comment by KirstieJane** [comment]
Thank you @ha0ye!! I was really hoping someone who knew more about R would come along to help me get this installation smoother!

Do you want to have a go at fixing the install and running binder in your fork of the repository? RStudio takes a long time to build for each binder update so I think it makes sense to test somewhere else and then incorporate the changes when we know it works.

Let me know if you don’t have time to work on this and I’ll add it to my to do list for next week (moving house this weekend!! 😱😱😱)

Thanks again for the help!!

**Comment by ha0ye** [comment]
Yep, I can take a look. and then work out a PR.

**Comment by KirstieJane** [comment]
💞💞 Thank you!! ✨✨
