### ISSUE TITLE
get AttributeError when import PtitPrince

### ISSUE THREAD

**Issue by XiaoyuZeng** [RainCloudPlots/RainCloudPlots#32]
Hi all,

I used to plot raincloud plot with python (PtitPrince), but today when I tried to import PtitPrince, I got some error "AttributeError: type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'"

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-67c3d644595f> in <module>()
      2 import numpy as np
      3 from pandas.core.frame import DataFrame
----> 4 import ptitprince as pt
      5 import seaborn as sns
      6 import os

D:\ProgramData\Anaconda3\lib\site-packages\ptitprince\__init__.py in <module>()
----> 1 from .PtitPrince import half_violinplot, RainCloud, stripplot

D:\ProgramData\Anaconda3\lib\site-packages\ptitprince\PtitPrince.py in <module>()
      3 import colorsys
      4 import numpy as np
----> 5 from scipy import stats
      6 import pandas as pd
      7 import matplotlib as mpl

D:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\__init__.py in <module>()
    343 from __future__ import division, print_function, absolute_import
    344 
--> 345 from .stats import *
    346 from .distributions import *
    347 from .morestats import *

D:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\stats.py in <module>()
    169 import scipy.special as special
    170 import scipy.linalg as linalg
--> 171 from . import distributions
    172 from . import mstats_basic
    173 from ._distn_infrastructure import _lazywhere

D:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\distributions.py in <module>()
      8 from __future__ import division, print_function, absolute_import
      9 
---> 10 from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
     11                                     rv_frozen)
     12 

D:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py in <module>()
     14 import warnings
     15 
---> 16 from scipy.misc import doccer
     17 from ._distr_params import distcont, distdiscrete
     18 from scipy._lib._util import check_random_state, _lazywhere, _lazyselect

D:\ProgramData\Anaconda3\lib\site-packages\scipy\misc\__init__.py in <module>()
     66 from numpy import who as _who, source as _source, info as _info
     67 import numpy as np
---> 68 from scipy.interpolate._pade import pade as _pade
     69 from scipy.special import (comb as _comb, logsumexp as _lsm,
     70         factorial as _fact, factorial2 as _fact2, factorialk as _factk)

D:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\__init__.py in <module>()
    173 from __future__ import division, print_function, absolute_import
    174 
--> 175 from .interpolate import *
    176 from .fitpack import *
    177 

D:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py in <module>()
     30 from . import _ppoly
     31 from .fitpack2 import RectBivariateSpline
---> 32 from .interpnd import _ndim_coords_from_arrays
     33 from ._bsplines import make_interp_spline, BSpline
     34 

D:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpnd.cp37-win_amd64.pyd in init scipy.interpolate.interpnd()

AttributeError: type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'

I'm not sure whether this error comes from some updates of PtitPrince. Does anyone get same problem?

FYI, I run this package on Windows 7, on jupyter lab.

**Comment by pog87** [comment]
Dear Xiaoyu Zeng,
thanks for using our package! From the error report it seems you have trouble with the `scipy` package. You could do the following steps:
 1. try to import seaborn before ptitprince, and check if the same error is still there.
2. uninstall and reinstall script

let us know!

**Comment by XiaoyuZeng** [comment]
> Dear Xiaoyu Zeng,
> thanks for using our package! From the error report it seems you have trouble with the `scipy` package. You could do the following steps:
> 
> 1. try to import seaborn before ptitprince, and check if the same error is still there.
> 2. uninstall and reinstall scipy
> 
> let us know!

Thanks for your reply! I tried to uninstall ptitprince and seaborn and scipy, and reinstall them. 

It works now.

Thanks again for your suggestions!

For anyone who encounters similar problems, it may help to pay attention to the versions of related package.
