### ISSUE TITLE
Configure the box plot (Python)

### ISSUE THREAD

**Issue by IchorPop** [RainCloudPlots/RainCloudPlots#36]
First of all, thank you for the great package! It's a great visualisation tool.

I'm looking to do two things, is there a way to do them?

1. Remove the box plot markers for outliers from the figure
2. Include the mean as a dashed line in the box plot
3. Change the whiskers to be based on percentiles

**Comment by IchorPop** [comment]
It seems that in the latest version of the master branch `https://github.com/pog87/PtitPrince/tree/master/ptitprince` the `RainCloud` function has the parameter `showfliers` which solves the first question. Is it possible for you to add a `showmeans` flag too?

**Comment by pog87** [comment]
Hi @IchorPop and thanks for your suggestion.
I'm currently studying a way for all the questions like "can I use *this* specific input in order to ...". 
please be patient.

**Comment by pog87** [comment]
Done!
from version `0.2.0` you can pass every possible kwarg to boxplot like this:
`pt.RainCloud(...., box_showfliers = True, box_showmeans = True, box_whis = ...)`
