### ISSUE TITLE
python binder tutorial fails when importing PtitPrince

### ISSUE THREAD

**Issue by mmagnuski** [RainCloudPlots/RainCloudPlots#42]
The python binder tutorial fails when importing `PtitPrince`:

```python-traceback
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-74cd4457d4e5> in <module>
     10 
     11 
---> 12 import ptitprince as pt

/srv/conda/envs/notebook/lib/python3.7/site-packages/ptitprince/__init__.py in <module>
----> 1 from .PtitPrince import half_violinplot, RainCloud, stripplot

/srv/conda/envs/notebook/lib/python3.7/site-packages/ptitprince/PtitPrince.py in <module>
     18 
     19 from seaborn import utils
---> 20 from seaborn.utils import iqr, categorical_order, remove_na
     21 from seaborn.algorithms import bootstrap
     22 from seaborn.palettes import color_palette, husl_palette, light_palette, dark_palette

ImportError: cannot import name 'categorical_order' from 'seaborn.utils' (/srv/conda/envs/notebook/lib/python3.7/site-packages/seaborn/utils.py)
```

**Comment by pog87** [comment]
it may be sufficient to update seaborn to the lastest version.

**Comment by KirstieJane** [comment]
The first cell in the binder link works for me - can you clarify how you got to that error @mmagnuski ?

![image](https://user-images.githubusercontent.com/3626306/94260556-4e8f2480-ff28-11ea-880a-26f39f7cd1d5.png)

**Comment by mmagnuski** [comment]
@KirstieJane I've entered through the "binder tutorial python" linked in the section "Interactive tutorials online" in the README. I tried again now, and have the same problem.

**Comment by KirstieJane** [comment]
Can you show me the same screenshot (but on your screen!) as the one I showed above?

You can copy the image from whereever and paste it into this comment box and it will show up 👍🏻

**Comment by mmagnuski** [comment]
![image](https://user-images.githubusercontent.com/8452354/94268248-2c53d180-ff3d-11ea-8bf5-c807e894e87e.png)

**Comment by mmagnuski** [comment]
If that is useful: the first time I entered this binder link the environement setup took very long and the log seemed to be full of conflicts and retries. But not it opens reasonably fast (about one minute).

**Comment by mmagnuski** [comment]
The python binder tutorial works ok now, so I'm closing the issue. :)
