### ISSUE TITLE
Problem importing ptitprince as pt: No module named 'seaborn._core'

### ISSUE THREAD

**Issue by PaulaBanca** [RainCloudPlots/RainCloudPlots#46]
I'm trying to import your package but I get the following error:

![Screenshot 2020-11-13 at 16 10 01](https://user-images.githubusercontent.com/21359159/99093916-0a84db80-25cb-11eb-92fb-24bbc96ac984.png)

It's weird to have this error as I have used previously seaborn without any problems. I have tried to uninstal and reinstal both seaborn and ptitprince but the error remains. Thanks for your brilliant work with these plots!

**Comment by pog87** [comment]
Hi @PaulaBanca thanks for using our package.
Did you try [this](https://github.com/pog87/PtitPrince/issues/16#issuecomment-701225906)?
