### ISSUE TITLE
No module named 'seaborn._core'

### ISSUE THREAD

**Issue by shoheiyamaguchi** [RainCloudPlots/RainCloudPlots#47]
I want to user your great raincloudplots. But, this error occured. What's going on ?

<img width="748" alt="スクリーンショット 2020-12-18 15 25 06" src="https://user-images.githubusercontent.com/48846835/102582092-37398f00-4145-11eb-88e7-87bfe7bdfccf.png">

**Comment by shoheiyamaguchi** [comment]
Error due to different versions

**Comment by guiomar** [comment]
Hi @shoheiyamaguchi what was the problem here? Could you indicate how to solve it? Thanks!

**Comment by catisf** [comment]
Hi - I am getting the exact same error, so could I ask when you say different version, what did you have different versions of? Python? Ptitprince? Seaborn? Thank you for any help!
