### ISSUE TITLE
ENH: Connection lines between every single data point

### ISSUE THREAD

**Issue by moritz-gerster** [RainCloudPlots/RainCloudPlots#67]
Thanks for this great library! 

I would love to see a feature that either doesn't exist in your package or I didn't find it. It is the reason why I installed your package, because I wanted to reproduce the very plot from your logo:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/45031224/205871167-43ff480d-51a0-4918-98d6-95c99a0d550e.png">

In that logo, there are grey connection lines between every single data point. How can I achieve this with your library?

Thank you!

Moritz

**Comment by njudd** [comment]
It is easily done with [njudd/ggrain](https://github.com/njudd/ggrain), with a combination of `id.long.var` & `line.args = list(color = "gray")`. 

Note the jitter seed for the position on point & line must be the same. CRAN did not allow us to set seeds in packages, yet we are working on fixing this.

**Comment by moritz-gerster** [comment]
> It is easily done in R with [njudd/ggrain](https://github.com/njudd/ggrain)

Thanks @njudd! So that means it is not possible in the Python implementation?

**Comment by njudd** [comment]
At this moment it is not possible in Python, feel free to branch [pog87/PtitPrince](https://github.com/pog87/PtitPrince) and add it!
